#!/usr/bin/env python3
"""
Generate db/seed/seed.sql — Riverbend demo data.

Deterministic (fixed RNG seed) so the committed seed.sql is reproducible. It
PRESERVES the hand-authored teaching fixtures verbatim:
  * Maria Gonzalez as THREE patient rows (1042, 1330, 1588) with the penicillin
    allergy recorded only under 1330 (duplicate-patient / no-MPI debt).
  * James O'Brien (1043) and Aisha Khan (1601).
  * Two confirmed appointments for the SAME slot 88231 ~400ms apart (retry race).
  * The PHI-laden audit_logs rows (audit-is-logging debt).
and then layers a few hundred realistic rows on top so the database reads like a
real, lived-in clinic network.

Run:  python3 db/seed/generate_seed.py  > db/seed/seed.sql
"""
import base64
import hashlib
import random
from datetime import datetime, timedelta

random.seed(2026)

# --- password hashing (django-style pbkdf2_sha256; mirrored in gateway/security) -
def hash_password(password: str, salt: str, iterations: int = 260000) -> str:
    dk = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), iterations)
    return f"pbkdf2_sha256${iterations}${salt}${base64.b64encode(dk).decode()}"

DEMO_PASSWORD = "portal123"   # all seeded accounts; documented in README/runbook

def sql_str(v):
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

OUT = []
def emit(line=""):
    OUT.append(line)

emit("-- Riverbend demo seed data. GENERATED by db/seed/generate_seed.py — do not")
emit("-- hand-edit; change the generator and re-run. Deterministic (seed=2026).")
emit("--")
emit("-- Teaching fixtures preserved verbatim: Maria Gonzalez triple (1042/1330/")
emit("-- 1588) with the penicillin allergy only under 1330; the double-booked slot")
emit("-- 88231; and the PHI-laden audit_logs rows.")
emit()

# ---------------------------------------------------------------------------
# users — everyone gets the single 'staff' role (role bloat / no least-privilege)
# ---------------------------------------------------------------------------
USERS = [
    ("mokonkwo",  "Maya Okonkwo (COO)"),
    ("frontdesk", "Front Desk (Riverbend Main)"),
    ("rdelgado",  "Rosa Delgado (Registration)"),
    ("jpark",     "Jin Park (Registration)"),
    ("drpatel",   "Dr. Anil Patel"),
    ("drnguyen",  "Dr. Anita Nguyen"),
    ("drlee",     "Dr. Sandra Lee"),
    ("billing1",  "Tom Reyes (Billing)"),
    ("roiclerk",  "Dana White (ROI Clerk)"),
    ("labtech",   "Lab Intake"),
    ("nurse_kc",  "Karen Cole, RN"),
    ("itadmin",   "Helix Support"),
]
# W4 / adr/0011: patient-portal accounts, each bound to the chart it owns.
#
# maria.gonzalez is bound to 1042 ON PURPOSE -- the fragment WITHOUT the
# penicillin allergy. She logs in and sees a chart missing her own allergy until
# the SAME_AS link spans her three fragments, which makes the W2 finding visible
# from the patient side rather than only in an eval report.
PATIENT_USERS = [
    ("maria.gonzalez", "Maria Gonzalez", 1042),
    ("james.obrien",   "James O'Brien",  1043),
]

emit("INSERT INTO users (id, username, password_hash, full_name, role, patient_id, created_at) VALUES")
rows = []
for i, (uname, full) in enumerate(USERS, start=1):
    salt = f"riverbend{i:02d}saltval0"  # fixed -> deterministic output
    h = hash_password(DEMO_PASSWORD, salt)
    rows.append(f" ({i}, {sql_str(uname)}, {sql_str(h)}, {sql_str(full)}, 'staff', NULL, now())")
for j, (uname, full, pid) in enumerate(PATIENT_USERS, start=len(USERS) + 1):
    salt = f"riverbend{j:02d}saltval0"
    h = hash_password(DEMO_PASSWORD, salt)
    rows.append(f" ({j}, {sql_str(uname)}, {sql_str(h)}, {sql_str(full)}, 'patient', NULL, now())")
emit(",\n".join(rows) + ";")
emit(f"SELECT setval('users_id_seq', {len(USERS) + len(PATIENT_USERS)}, true);")
emit()

# ---------------------------------------------------------------------------
# patients — fixtures first, then ~250 generated
# ---------------------------------------------------------------------------
emit("INSERT INTO patients (id, mrn, name, dob, ssn, gender, address, phone, email, notes, created_via, created_at) VALUES")
fixture_patients = [
    (1042, "M4471", "Maria Gonzalez", "1971-03-02", "412-55-9981", "F", "118 Maple Ave, Beverly Hills, CA 90210", "310-555-0147", "maria.g@example.com", "Prefers morning appts.", "self_service", "2026-06-22 09:14:06"),
    (1043, "M5012", "James O'Brien",  "1958-11-19", "501-22-7734", "M", "42 Birch St, Riverbend, CA 90211", "310-555-0199", "jobrien@example.com", "Hard of hearing.", "self_service", "2026-06-22 09:17:27"),
    (1330, "M4471", "Maria Gonzales", "1971-03-02", "412-55-9981", "F", "118 Maple Ave, Beverly Hills, CA 90210", "310-555-0147", "maria.g@example.com", "PCN allergy noted at front desk.", "self_service", "2026-06-22 09:21:45"),
    (1588, "M4471", "M. Gonzalez",    "1971-02-03", "412-55-9981", "F", "118 Maple Ave, Beverly Hills, CA 90210", "310-555-0147", None, "", "self_service", "2026-06-22 09:55:06"),
    (1601, "M6620", "Aisha Khan",     "1989-07-14", "623-41-2210", "F", "900 Cedar Rd, Riverbend, CA 90211", "310-555-0210", "akhan@example.com", "", "front_desk", "2026-06-23 10:02:00"),
]
FIRST = ["James","Mary","Robert","Patricia","John","Jennifer","Michael","Linda","David","Elizabeth",
         "William","Barbara","Richard","Susan","Joseph","Jessica","Thomas","Karen","Aisha","Wei",
         "Carlos","Fatima","Hiroshi","Olga","Samuel","Grace","Derek","Nadia","Luis","Priya",
         "Marcus","Helen","Andre","Sofia","Victor","Renee","Omar","Beatriz","Ethan","Maya"]
LAST = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez",
        "Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin",
        "Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson",
        "Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Khan","Okafor"]
STREETS = ["Maple Ave","Birch St","Cedar Rd","Oak Ln","Pine St","Elm Dr","Sunset Blvd","River Rd",
           "Lake Ave","Hill St","2nd St","Park Pl","Mission Rd","Valley Way","Grand Ave"]
CITIES = [("Riverbend","90211"),("Beverly Hills","90210"),("Glendale","91201"),
          ("Pasadena","91101"),("Burbank","91502"),("Inglewood","90301")]
GENDERS = ["F","M","M","F","X"]

prows = []
for p in fixture_patients:
    pid, mrn, name, dob, ssn, g, addr, phone, email, notes, via, created = p
    prows.append(f" ({pid}, {sql_str(mrn)}, {sql_str(name)}, {sql_str(dob)}, {sql_str(ssn)}, {sql_str(g)}, {sql_str(addr)}, {sql_str(phone)}, {sql_str(email)}, {sql_str(notes)}, {sql_str(via)}, {sql_str(created)})")

gen_patient_ids = []
pid = 1602
for _ in range(250):
    first = random.choice(FIRST); last = random.choice(LAST)
    name = f"{first} {last}"
    year = random.randint(1940, 2007); month = random.randint(1,12); day = random.randint(1,28)
    dob = f"{year:04d}-{month:02d}-{day:02d}"
    ssn = f"{random.randint(200,699):03d}-{random.randint(10,99):02d}-{random.randint(1000,9999):04d}"
    g = random.choice(GENDERS)
    city, zc = random.choice(CITIES)
    addr = f"{random.randint(10,9999)} {random.choice(STREETS)}, {city}, CA {zc}"
    phone = f"310-555-{random.randint(0,9999):04d}"
    email = f"{first.lower()}.{last.lower()}{random.randint(1,99)}@example.com"
    mrn = f"M{random.randint(1000,9999)}"
    via = random.choice(["self_service","front_desk","front_desk"])
    days_ago = random.randint(5, 1500)
    created = (datetime(2026,6,20) - timedelta(days=days_ago)).strftime("%Y-%m-%d %H:%M:%S")
    notes = random.choice(["", "", "", "Prefers afternoon appts.", "Spanish-speaking.",
                           "Wheelchair access needed.", "No known issues.", "Follow-up requested."])
    prows.append(f" ({pid}, {sql_str(mrn)}, {sql_str(name)}, {sql_str(dob)}, {sql_str(ssn)}, {sql_str(g)}, {sql_str(addr)}, {sql_str(phone)}, {sql_str(email)}, {sql_str(notes)}, {sql_str(via)}, {sql_str(created)})")
    gen_patient_ids.append(pid)
    pid += 1
emit(",\n".join(prows) + ";")
max_pid = pid - 1
emit(f"SELECT setval('patients_id_seq', {max_pid}, true);")
emit()

# W4 / adr/0011: bind the patient-portal logins to their charts. Done here rather
# than in the users INSERT because the FK requires the patients rows to exist.
emit("-- W4/adr-0011: bind patient-portal logins to the chart they own.")
for uname, _full, pid in PATIENT_USERS:
    emit(f"UPDATE users SET patient_id = {pid} WHERE username = {sql_str(uname)};")
emit()

all_patient_ids = [1042,1043,1330,1588,1601] + gen_patient_ids

# ---------------------------------------------------------------------------
# providers
# ---------------------------------------------------------------------------
PROVIDERS = [
    (1,"Dr. Anil Patel","Family Medicine","Riverbend Main"),
    (2,"Dr. Anita Nguyen","Internal Medicine","Riverbend Main"),
    (3,"Dr. Sandra Lee","Pediatrics","Riverbend North"),
    (4,"Dr. Omar Haddad","Cardiology","Riverbend Main"),
    (5,"Dr. Grace Kim","Dermatology","Riverbend North"),
    (6,"Lab Services","Laboratory","Riverbend Main"),
    (7,"Imaging Center","Radiology","Riverbend Main"),
    (8,"Dr. Beatriz Alvarez","OB/GYN","Riverbend South"),
]
emit("INSERT INTO providers (id, name, specialty, location) VALUES")
emit(",\n".join(f" ({i}, {sql_str(n)}, {sql_str(s)}, {sql_str(l)})" for i,n,s,l in PROVIDERS) + ";")
emit(f"SELECT setval('providers_id_seq', {len(PROVIDERS)}, true);")
emit()

# ---------------------------------------------------------------------------
# slots — explicit ids incl. 88231 (double-booked) and 88240
# ---------------------------------------------------------------------------
emit("INSERT INTO slots (id, provider_id, location, start_at, end_at, status) VALUES")
srows = []
slot_id = 88200
booked_ids = {88231, 88240}
base = datetime(2026, 6, 23, 8, 0, 0)
for n in range(120):
    prov = random.randint(1,8)
    loc = PROVIDERS[prov-1][3]
    start = base + timedelta(days=n // 8, hours=(n % 8))
    end = start + timedelta(minutes=30)
    status = "booked" if slot_id in booked_ids else random.choice(["open","open","open","booked"])
    srows.append(f" ({slot_id}, {prov}, {sql_str(loc)}, {sql_str(start.strftime('%Y-%m-%d %H:%M:%S'))}, {sql_str(end.strftime('%Y-%m-%d %H:%M:%S'))}, {sql_str(status)})")
    slot_id += 1
emit(",\n".join(srows) + ";")
emit(f"SELECT setval('slots_id_seq', {slot_id-1}, true);")
emit()

# ---------------------------------------------------------------------------
# insurance_coverages
# ---------------------------------------------------------------------------
PAYERS = [("Blue Cross Blue Shield","PPO"),("Aetna","PPO"),("UnitedHealthcare","HMO"),
          ("Cigna","PPO"),("Kaiser","HMO"),("Medi-Cal","Medicaid"),("Medicare","Medicare"),
          (None,"self_pay")]
emit("INSERT INTO insurance_coverages (patient_id, payer_name, member_id, group_number, plan_type, status, verified_at) VALUES")
irows = []
# fixtures: Maria's three rows all BCBS4471 (same member id across dup charts)
for pid_ in (1042, 1330, 1588):
    irows.append(f" ({pid_}, 'Blue Cross Blue Shield', 'BCBS4471', 'GRP88', 'PPO', 'active', '2026-06-22 09:14:30')")
irows.append(f" (1043, 'Aetna', 'AETNA9920', 'GRP12', 'PPO', 'active', '2026-06-22 09:17:50')")
for pid_ in all_patient_ids:
    if pid_ in (1042,1330,1588,1043):
        continue
    payer, plan = random.choice(PAYERS)
    if payer is None:
        irows.append(f" ({pid_}, NULL, NULL, NULL, 'self_pay', 'unknown', NULL)")
    else:
        mid = f"{payer.split()[0][:4].upper()}{random.randint(1000,9999)}"
        status = random.choice(["active","active","active","inactive","unknown"])
        ver = "'2026-06-01 12:00:00'" if status != "unknown" else "NULL"
        irows.append(f" ({pid_}, {sql_str(payer)}, {sql_str(mid)}, 'GRP{random.randint(10,99)}', {sql_str(plan)}, {sql_str(status)}, {ver})")
emit(",\n".join(irows) + ";")
emit()

# ---------------------------------------------------------------------------
# encounters — fixtures (ids 1-5) then generated
# ---------------------------------------------------------------------------
emit("INSERT INTO encounters (id, patient_id, encounter_type, provider, reason, location, status, summary, allergies, medications, occurred_at) VALUES")
erows = [
    " (1, 1042, 'office_visit', 'Dr. Patel',  'Annual physical', 'Riverbend Main', 'finished', 'Annual physical. Unremarkable.', '', 'lisinopril', '2026-01-12 09:00:00')",
    " (2, 1330, 'office_visit', 'Dr. Nguyen', 'Sinus infection', 'Riverbend Main', 'finished', 'Sinus infection. Prescribed antibiotic.', 'penicillin', 'amoxicillin', '2026-03-04 11:30:00')",
    " (3, 1588, 'lab',          'Lab',        'CBC panel', 'Riverbend Main', 'finished', 'CBC panel within normal limits.', '', '', '2026-05-19 08:15:00')",
    " (4, 1043, 'office_visit', 'Dr. Patel',  'Hearing aid follow-up', 'Riverbend Main', 'finished', 'Hearing aid follow-up.', '', '', '2026-02-20 14:00:00')",
    " (5, 1601, 'office_visit', 'Dr. Nguyen', 'New patient intake', 'Riverbend Main', 'finished', 'New patient intake.', 'none known', '', '2026-06-23 10:30:00')",
]
ETYPES = ["office_visit","office_visit","lab","imaging","telehealth"]
REASONS = ["Annual physical","Follow-up","Acute visit","Lab draw","Imaging","Med refill","Consult"]
ALLERGY_POOL = ["", "", "", "penicillin", "sulfa", "latex", "peanuts", "none known"]
MED_POOL = ["", "", "lisinopril", "metformin", "atorvastatin", "albuterol", "levothyroxine", "amoxicillin"]
enc_id = 6
enc_by_patient = {}
for pid_ in all_patient_ids:
    n_enc = random.choices([0,1,2,3,4],[1,4,4,2,1])[0]
    for _ in range(n_enc):
        prov = random.choice(PROVIDERS)
        etype = random.choice(ETYPES)
        reason = random.choice(REASONS)
        days_ago = random.randint(1, 1200)
        occ = (datetime(2026,6,20) - timedelta(days=days_ago)).strftime("%Y-%m-%d %H:%M:%S")
        summ = f"{reason}. {random.choice(['Stable.','Improving.','No acute distress.','Counseled patient.','Routine.'])}"
        allergies = random.choice(ALLERGY_POOL)
        meds = random.choice(MED_POOL)
        erows.append(f" ({enc_id}, {pid_}, {sql_str(etype)}, {sql_str(prov[1])}, {sql_str(reason)}, {sql_str(prov[3])}, 'finished', {sql_str(summ)}, {sql_str(allergies)}, {sql_str(meds)}, {sql_str(occ)})")
        enc_by_patient.setdefault(pid_, []).append(enc_id)
        enc_id += 1
# ensure fixtures map
for k,v in {1042:[1],1330:[2],1588:[3],1043:[4],1601:[5]}.items():
    enc_by_patient.setdefault(k, []).extend(v)
emit(",\n".join(erows) + ";")
emit(f"SELECT setval('encounters_id_seq', {enc_id-1}, true);")
emit()

# ---------------------------------------------------------------------------
# records — fixtures (ids 1-5) then generated (no index on body = full scan)
# ---------------------------------------------------------------------------
emit("INSERT INTO records (id, encounter_id, patient_id, kind, title, body, status, reference_range, created_at) VALUES")
rrows = [
    " (1, 1, 1042, 'note', 'Visit note', 'Patient in good health.', 'final', NULL, '2026-01-12 09:20:00')",
    " (2, 2, 1330, 'note', 'Visit note', 'Penicillin allergy confirmed. Switched to non-PCN class.', 'final', NULL, '2026-03-04 11:45:00')",
    " (3, 3, 1588, 'lab_result', 'CBC panel', 'WBC 6.1, RBC 4.7, Hgb 14.2.', 'normal', 'WBC 4.0-11.0; Hgb 13.5-17.5', '2026-05-19 09:00:00')",
    " (4, 4, 1043, 'note', 'Visit note', 'Hearing stable.', 'final', NULL, '2026-02-20 14:20:00')",
    " (5, 5, 1601, 'note', 'Visit note', 'Established care.', 'final', NULL, '2026-06-23 10:50:00')",
]
LAB_TESTS = [("CBC panel","WBC 6.1, RBC 4.7, Hgb 14.2.","WBC 4.0-11.0; Hgb 13.5-17.5"),
             ("Lipid panel","Total chol 188, LDL 102, HDL 55.","LDL <130; HDL >40"),
             ("A1c","6.2%.","<5.7% normal; 5.7-6.4% prediabetes"),
             ("Basic metabolic","Na 140, K 4.1, Cr 0.9.","Na 135-145; K 3.5-5.1"),
             ("TSH","2.3 mIU/L.","0.4-4.0 mIU/L")]
rec_id = 6
for pid_, encs in enc_by_patient.items():
    for e in encs:
        if e <= 5:
            continue
        for _ in range(random.choices([1,1,2,3],[3,3,2,1])[0]):
            kind = random.choice(["note","note","lab_result","imaging","immunization"])
            if kind == "lab_result":
                t,b,rr = random.choice(LAB_TESTS)
                status = random.choice(["normal","normal","abnormal","preliminary"])
                rrows.append(f" ({rec_id}, {e}, {pid_}, 'lab_result', {sql_str(t)}, {sql_str(b)}, {sql_str(status)}, {sql_str(rr)}, now())")
            elif kind == "imaging":
                rrows.append(f" ({rec_id}, {e}, {pid_}, 'imaging', 'Imaging report', {sql_str(random.choice(['Chest X-ray: no acute findings.','Knee MRI: mild effusion.','Abdominal US: unremarkable.']))}, 'final', NULL, now())")
            elif kind == "immunization":
                rrows.append(f" ({rec_id}, {e}, {pid_}, 'immunization', 'Immunization', {sql_str(random.choice(['Influenza vaccine administered.','Tdap administered.','COVID-19 booster administered.']))}, 'final', NULL, now())")
            else:
                rrows.append(f" ({rec_id}, {e}, {pid_}, 'note', 'Visit note', {sql_str(random.choice(['Patient stable.','Continue current plan.','Labs reviewed.','Counseled on diet/exercise.','RTC in 6 months.']))}, 'final', NULL, now())")
            rec_id += 1
emit(",\n".join(rrows) + ";")
emit(f"SELECT setval('records_id_seq', {rec_id-1}, true);")
emit()

# ---------------------------------------------------------------------------
# appointments — fixtures (double-booked slot 88231) then generated
# ---------------------------------------------------------------------------
emit("INSERT INTO appointments (patient_id, slot_id, provider, reason, location, scheduled_for, status, created_at) VALUES")
arows = [
    " (1042, 88231, 'Dr. Patel', 'Follow-up', 'Riverbend Main', '2026-06-26 08:00:00', 'confirmed', '2026-06-22 09:31:04.120')",
    " (1588, 88231, 'Dr. Patel', 'Follow-up', 'Riverbend Main', '2026-06-26 08:00:00', 'confirmed', '2026-06-22 09:31:04.519')",
    " (1043, 88240, 'Dr. Nguyen', 'Hearing follow-up', 'Riverbend Main', '2026-06-27 09:00:00', 'confirmed', '2026-06-22 10:05:00.000')",
]
for pid_ in all_patient_ids:
    for _ in range(random.choices([0,1,2],[2,3,1])[0]):
        prov = random.choice(PROVIDERS)
        s_id = random.randint(88200, slot_id-1)
        reason = random.choice(REASONS)
        days_fwd = random.randint(1, 30)
        sched = (datetime(2026,6,24) + timedelta(days=days_fwd, hours=random.randint(0,8))).strftime("%Y-%m-%d %H:%M:%S")
        status = random.choice(["confirmed","confirmed","confirmed","cancelled","completed"])
        created = (datetime(2026,6,1) + timedelta(days=random.randint(0,20))).strftime("%Y-%m-%d %H:%M:%S")
        arows.append(f" ({pid_}, {s_id}, {sql_str(prov[1])}, {sql_str(reason)}, {sql_str(prov[3])}, {sql_str(sched)}, {sql_str(status)}, {sql_str(created)})")
emit(",\n".join(arows) + ";")
emit()

# ---------------------------------------------------------------------------
# consents
# ---------------------------------------------------------------------------
emit("INSERT INTO consents (patient_id, kind, signed_at) VALUES")
crows = [
    " (1042, 'npp_ack', now())", " (1042, 'treatment_consent', now())",
    " (1043, 'npp_ack', now())", " (1601, 'npp_ack', now())",
]
for pid_ in gen_patient_ids:
    if random.random() < 0.85:
        crows.append(f" ({pid_}, 'npp_ack', now())")
    if random.random() < 0.7:
        crows.append(f" ({pid_}, 'treatment_consent', now())")
emit(",\n".join(crows) + ";")
emit()

# ---------------------------------------------------------------------------
# roi_requests — note: NO authorization linkage captured (164.508 not enforced)
# ---------------------------------------------------------------------------
emit("INSERT INTO roi_requests (patient_id, requested_by, recipient, recipient_type, purpose, date_range_start, date_range_end, status, created_at) VALUES")
RECIP = [("Dr. Smith Cardiology","provider"),("Acme Law LLP","attorney"),
         ("BlueCross Claims","payer"),("Patient (self)","self"),("County Health","provider")]
PURP = ["Continuity of care","Legal matter","Insurance claim","Personal copy","Referral"]
rqrows = []
for _ in range(16):
    pid_ = random.choice(all_patient_ids)
    recip, rtype = random.choice(RECIP)
    purpose = random.choice(PURP)
    status = random.choice(["pending","pending","fulfilled","denied"])
    created = (datetime(2026,5,1) + timedelta(days=random.randint(0,55))).strftime("%Y-%m-%d %H:%M:%S")
    rqrows.append(f" ({pid_}, {sql_str(random.choice(['roiclerk','frontdesk','billing1']))}, {sql_str(recip)}, {sql_str(rtype)}, {sql_str(purpose)}, '2024-01-01', '2026-06-01', {sql_str(status)}, {sql_str(created)})")
emit(",\n".join(rqrows) + ";")
emit()

# ---------------------------------------------------------------------------
# disclosures — historical releases, missing authorization/purpose linkage
# ---------------------------------------------------------------------------
emit("INSERT INTO disclosures (patient_id, roi_request_id, disclosed_to, disclosed_at) VALUES")
drows = []
for i in range(8):
    pid_ = random.choice(all_patient_ids)
    drows.append(f" ({pid_}, NULL, {sql_str(random.choice([r[0] for r in RECIP]))}, {sql_str((datetime(2026,5,5)+timedelta(days=i*4)).strftime('%Y-%m-%d %H:%M:%S'))})")
emit(",\n".join(drows) + ";")
emit()

# ---------------------------------------------------------------------------
# audit_logs — "audit" rows are really app INFO logs with PHI in them
# ---------------------------------------------------------------------------
emit("INSERT INTO audit_logs (actor, message) VALUES")
alrows = [
    " ('intake-service', 'POST /intake body={\"name\":\"Maria Gonzalez\",\"dob\":\"1971-03-02\",\"ssn\":\"412-55-9981\"}')",
    " ('records-service', 'GET /patients/1042/records 200')",
]
for _ in range(20):
    pid_ = random.choice(all_patient_ids)
    alrows.append(f" ('records-service', {sql_str(f'GET /patients/{pid_}/records 200')})")
emit(",\n".join(alrows) + ";")
emit()

print("\n".join(OUT))
